# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='end_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sections',
            name='link',
            field=models.CharField(blank=True, default=b'', max_length=1024),
        ),
        migrations.AddField(
            model_name='sections',
            name='start_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default=b'https://img.shields.io/badge/website-_simpread.ksria.com-1DBA90.svg', max_length=256),
        ),
    ]
