# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=b'', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True)),
                ('origin', models.URLField(default=b'', null=True)),
                ('highlight', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=True)),
                ('is_video', models.BooleanField(default=False)),
                ('image', models.URLField(default=b'', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.User'),
        ),
    ]
