# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180722_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default=b'https://audionetwork.oss-cn-beijing.aliyuncs.com/markone/avatar_02.png', max_length=256),
        ),
    ]
