# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-03 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180726_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('status', models.BooleanField(default=True)),
                ('send', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default=b'https://audionetwork.oss-cn-beijing.aliyuncs.com/markone/avatar_05.png', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
